Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /account/lwhoami
Not Found: /account/lwhoami/
Authenticated user: youssef bouchmama
/home/youssef/login/login/views/logout.py changed, reloading.
Watching for file changes with StatReloader
User youssef bouchmama is logging out.
User  has logged out successfully.
Unauthenticated access attempt
Unauthorized: /account/whoami/
/home/youssef/login/login/views/logout.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/whoami.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /account/whoami/
Internal Server Error: /account/login/42/
Traceback (most recent call last):
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/youssef/login/login/views/login_redirections.py", line 22, in login_42
    url += f"?client_id={settings.SOCIAL_AUTH_42_OAUTH2_KEY}"
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'SOCIAL_AUTH_42_OAUTH2_KEY'
/home/youssef/login/project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /account/whoami/
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /account/whoami/
Not Found: /account/google/42
Not Found: /account/google/42/
Not Found: /account/login/google/42/
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /account/login/42/
Traceback (most recent call last):
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/youssef/login/login/views/login_redirections.py", line 21, in login_42
    print(os.environ['SOCIAL_AUTH_42_OAUTH2_KEY'])
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 716, in __getitem__
KeyError: 'SOCIAL_AUTH_42_OAUTH2_KEY'
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
Watching for file changes with StatReloader
Bad Request: /account/login/callback/
Not Found: /favicon.ico
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
Bad Request: /account/login/callback/
Bad Request: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): oauth2.googleapis.com:443
https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /account/login/callback/
Traceback (most recent call last):
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/youssef/login/login/views/callback.py", line 56, in callback
    if req.session['state'] != req.GET.get('state'):
       ~~~~~~~~~~~^^^^^^^^^
  File "/home/youssef/login/venv/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'state'
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 401 None
Unauthorized: /account/login/callback/
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
Starting new HTTPS connection (1): api.intra.42.fr:443
https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
Starting new HTTPS connection (1): oauth2.googleapis.com:443
https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
Starting new HTTPS connection (1): www.googleapis.com:443
https://www.googleapis.com:443 "GET /oauth2/v1/userinfo HTTP/1.1" 200 None
/home/youssef/login/login/views/callback.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/login_redirections.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/login/views/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/youssef/login/project/settings.py changed, reloading.
Watching for file changes with StatReloader
